import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { StoreProvider } from '@/redux/StoreProvider';
import { ThemeProvider } from '@mui/material/styles';
import theme from '../theme';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
    title: 'Wellcome - HabitHub',
    description: 'Generated by create next app',
};
export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <StoreProvider>
            <ThemeProvider theme={theme}>
                <html lang="en">
                    <body className={inter.className}>
                        <div style={{ height: '776px' }}>{children}</div>
                    </body>
                </html>
            </ThemeProvider>
        </StoreProvider>
    );
}
