import type { Metadata } from 'next';
import { store } from '../app/redux/store';
import { Provider } from 'react-redux';
import { Inter } from 'next/font/google';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
    title: 'Wellcome - HabitHub',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <Provider store={store}>
            <html lang="en">
                <body className={inter.className}>{children}</body>
            </html>
        </Provider>
    );
}
