import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { StoreProvider } from '@/redux/StoreProvider';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
    title: 'Wellcome - HabitHub',
    description: 'Generated by create next app',
};
export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <StoreProvider>
            <html lang="en">
                <body className={inter.className}>
                    <div style={{ height: '750px' }}>{children}</div>
                </body>
            </html>
        </StoreProvider>
    );
}
